// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ImageStreamerApp",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0"),
        .tvOS("16.0"),
        .watchOS("9.0")
    ],
    products: [
        .iOSApplication(
            name: "ImageStreamerApp",
            targets: ["AppModule"],
            bundleIdentifier: "com.nomasystems.imagestreamer.ImageStreamerApp",
            teamIdentifier: "JM8BMXQ5NG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .note),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ImageStreamer", package: "imagestreamer")
            ],
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)

